### PR TITLE
Employer index

### PR DESCRIPTION
**Pull request by ciremoussadia**
Only admin avatars can edit or delete an employer.

### CODE REVIEW

**Comment by mikeymicrophone** [comment]
This looks pretty good.  The biggest problem is that you removed the directive 'can manage :all' from the ability regime.

The directives are applied in order, so by adding the more restrictive ones below that, they override the particulars.

Starting with full permission and restricting from there is more convention-over-configuration than adding directives for every action on every resource.

The app may still work well for you, since we haven't fully plugged in the helpers `load_and_authorize_resource` and `can?`.

**Comment by mikeymicrophone** [comment]
The names of the helpers are not quite right.  The delete link still mentions employer, although it can be used for any resource.  And the edit one doesn't need the term 'generate'.  Name it after its result, which is the link.  `edit_link_for` is totally fine.

**Comment by ciremoussadia** [comment]
Ok Got it.

**Comment by ciremoussadia** [comment]
@mikeymicrophone can u review this?

**Pull request closed without merging**
